apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    name: requesthandler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32134