kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-runner
subjects:
- kind: ServiceAccount
  name: test-runner
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # TODO: create cluster role with only required permissions
  apiGroup: rbac.authorization.k8s.io
