kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-runner
subjects:
- kind: ServiceAccount
  name: test-runner
roleRef:
  kind: Role
  name: test-runner
  apiGroup: rbac.authorization.k8s.io
